###
# About/contact for the site author
#
# name of the author of the site
name = "Lucas Joviniano"
# description to display in the sidebar
description = "Um <span class=\"codinfox-changing-keywords\"><b class=\"visible\">desenvolvedor</b><b class=\"hidden\">pesquisador</b></span>curioso e inspirado."

# the profile image of the author to display in the sidebar
gravatar = "217eb15e72a63d3a152a09cfca709bb2" # md5 hash of your email address # sidebar.html

# contact links to reach the author
#  - `name` is the font-awesome char name
#  - `path` is the link to follow 
contact = [
  { name = "linkedin", path = "https://www.linkedin.com/in/lucasjoviniano/" },
  { name = "github", path = "https://github.com/lucasjoviniano" },
  # { name = "facebook", path = "https://" },
  # { name = "twitter", path = "https://twitter.com/svavs" },
  { name = "instagram", path = "https://www.instagram.com/lucas.joviniano/" },
  { name = "lastfm", path = "https://www.last.fm/pt/user/lucasjoviniano" },
  { name = "film", path = "https://letterboxd.com/lucasjoviniano/" },
  # { name = "tumblr", path = "http://svavs.tumblr.com/" },
  { name = "email", path = "mailto:lucasjoviniano1@gmail.com" }
]