# The URL the site will be built for
base_url = "https://lucasjoviniano.github.io"
title = "Lucas Joviniano"
description = "Código. Livros. Linguagens."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "codinfox-zola"

generate_feed = true

taxonomies = [
  {name = "tags", lang = "en"},
  {name = "categories", feed = true, lang = "en"},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
logo = "/logo.png"

version = "0.0.1"
copyrightyear = "2022"

# Plugins
mathjax = true # whether support mathjax
google_analytics_token = "" # a UA-00000000-1 like code or leave blank if you don't want google analytics
disqus_short_name = "codinfox-zola" # leave blank if you don't want disqus

tag_page = "/tags/"
category_page = "/categories/"

image = "/img/curiosity_by_starsinmyfingertips_dakioyj-fullview.jpg"  # image for the home page
caption = "Original Artwork &copy; <a href=\"https://www.deviantart.com/starsinmyfingertips/art/Curiosity-639126235\">2016 - 2020 StarsInMyFingertips</a>"  # caption for the home page image

read_time = true